services:
  proyecto1php:
    image: php:8.3-apache
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
      - "./.docker/apache/apache.conf:/etc/apache2/sites-enable/000-default.conf"

  mariadb:
    image: mariadb:latest
    container_name: netblixdb
    environment:
      MARIADB_DATABASE: netflix
      MARIADB_USER: ismael
      MARIADB_PASSWORD: ismael
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:
